name: Build and Test app
on:
  push:
    branches: [base]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_XCODEPROJECT: ${{ 'Smash-up.xcodeproj' }}
      XC_SCHEME: ${{ 'Smash-Up' }}
    steps:
      - name: coherent-swift
        uses: arthurpalves/coherent-swift@0.5.5
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
      - uses: actions/checkout@v2
      - name: Run Unit and UI Tests
        run: /usr/bin/xcodebuild test -project "$XC_XCODEPROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
